# Site wide configuration

title: "STEMLab"
description: "Spatio Temporal Databases Laboratory site"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US

url: ""
base_url: "/web"

feed:
  path: atom.xml


# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll/scholar


# Site owner
owner:
  name: "STEMLab"
  web: ""
  twitter: ""
  bio: "stupid azamat."
  avatar:
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname:

# members order
members-order:
 - professor
 - postdoctor
 - phd
 - master
 - staff
 - parttime
 - internship
 - undergraduated

# Scholar settings
scholar:
  style: /_publications/stem_apa.csl
  locale: en

  sort_by: year
  order: descending

  source: /_publications
  bibliography: bibliography.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  query: "@*"

include:
  - .htaccess
  - publications/pubs-korean.html
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
